TOPDIR ?= ../..
include $(TOPDIR)/.config

$(FERNMELDER_SUPPORT)_SRC += services/fernmelder/fernmelder.c
$(FERNMELDER_SUPPORT)_SRC += services/fernmelder/scrollstring.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
